# Generated by Django 5.2.5 on 2026-03-25 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_job_earnings_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='deadline',
            field=models.DateField(default='2026-04-01'),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name='job',
            old_name='client',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='job',
            name='freelancer',
        ),
        migrations.RemoveField(
            model_name='job',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='OPEN', max_length=20),
        ),
    ]
