# Generated by Django 5.2.5 on 2026-03-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='User phone number', max_length=20, null=True),
        ),
    ]
