# Generated by Django 5.2.5 on 2026-03-25 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='+254000000000', help_text='Phone number in E.164 format (e.g., +254712345678)', max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in E.164 format: +[country code][number]. Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
